import * as stylex from '@stylexjs/stylex';

export const stylexVars = stylex.defineConsts({
  borderDefault: 'var(--yxgui-border-default)',
  borderFocus: 'var(--yxgui-border-focus)',
  borderStrong: 'var(--yxgui-border-strong)',
  componentsButtonActiveOffset: 'var(--yxgui-components-button-active-offset)',
  componentsButtonDisabledOpacity: 'var(--yxgui-components-button-disabled-opacity)',
  componentsButtonMinHeightLg: 'var(--yxgui-components-button-min-height-lg)',
  componentsButtonMinHeightMd: 'var(--yxgui-components-button-min-height-md)',
  componentsButtonMinHeightSm: 'var(--yxgui-components-button-min-height-sm)',
  componentsButtonPaddingLg: 'var(--yxgui-components-button-padding-lg)',
  componentsButtonPaddingMd: 'var(--yxgui-components-button-padding-md)',
  componentsButtonPaddingSm: 'var(--yxgui-components-button-padding-sm)',
  componentsButtonPrimaryHoverShadow: 'var(--yxgui-components-button-primary-hover-shadow)',
  componentsCardShadow: 'var(--yxgui-components-card-shadow)',
  componentsInputInvalidBorder: 'var(--yxgui-components-input-invalid-border)',
  controlBackground: 'var(--yxgui-control-background)',
  controlBackgroundDisabled: 'var(--yxgui-control-background-disabled)',
  controlBorder: 'var(--yxgui-control-border)',
  controlBorderFocus: 'var(--yxgui-control-border-focus)',
  controlForeground: 'var(--yxgui-control-foreground)',
  controlPlaceholder: 'var(--yxgui-control-placeholder)',
  paletteForeground: 'var(--yxgui-palette-foreground)',
  paletteMutedForeground: 'var(--yxgui-palette-muted-foreground)',
  radiusMd: 'var(--yxgui-radius-md)',
  radiusSm: 'var(--yxgui-radius-sm)',
  spacingLg: 'var(--yxgui-spacing-lg)',
  spacingSm: 'var(--yxgui-spacing-sm)',
  spacingXs: 'var(--yxgui-spacing-xs)',
  surfaceElevated: 'var(--yxgui-surface-elevated)',
  typographyFontFamily: 'var(--yxgui-typography-font-family)',
  typographyFontSizeLg: 'var(--yxgui-typography-font-size-lg)',
  typographyFontSizeMd: 'var(--yxgui-typography-font-size-md)',
  typographyFontSizeSm: 'var(--yxgui-typography-font-size-sm)',
  typographyFontWeightStrong: 'var(--yxgui-typography-font-weight-strong)',
  typographyLineHeightTight: 'var(--yxgui-typography-line-height-tight)',
  variantsGhostForeground: 'var(--yxgui-variants-ghost-foreground)',
  variantsGhostHoverBackground: 'var(--yxgui-variants-ghost-hover-background)',
  variantsOutlineBorder: 'var(--yxgui-variants-outline-border)',
  variantsOutlineForeground: 'var(--yxgui-variants-outline-foreground)',
  variantsPrimaryBackground: 'var(--yxgui-variants-primary-background)',
  variantsPrimaryForeground: 'var(--yxgui-variants-primary-foreground)',
  variantsSecondaryBackground: 'var(--yxgui-variants-secondary-background)',
  variantsSecondaryBorder: 'var(--yxgui-variants-secondary-border)',
  variantsSecondaryForeground: 'var(--yxgui-variants-secondary-foreground)',
  variantsSecondaryHoverBorder: 'var(--yxgui-variants-secondary-hover-border)'
});
