import * as stylex from '@stylexjs/stylex';
import { colors } from '../theme/colors.stylex';
import {
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  radii,
  spacing
} from '../theme/foundations.stylex';

export const overlayStyles = stylex.create({
  trigger: {
    alignItems: 'center',
    backgroundColor: { default: colors.primary, ':hover': colors.primaryHover },
    borderColor: 'transparent',
    borderRadius: radii.sm,
    borderStyle: 'solid',
    borderWidth: '1px',
    color: colors.onEmphasis,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semibold,
    gap: spacing.sm,
    justifyContent: 'center',
    lineHeight: lineHeights.sm,
    paddingBlock: spacing.md,
    paddingInline: spacing.lg
  },
  iconTrigger: {
    alignItems: 'center',
    backgroundColor: { default: colors.surfaceElevated, ':hover': colors.surfaceSubtle },
    borderColor: colors.borderMuted,
    borderRadius: radii.sm,
    borderStyle: 'solid',
    borderWidth: '1px',
    color: colors.text,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.sm,
    justifyContent: 'center',
    lineHeight: lineHeights.sm,
    minHeight: '36px',
    minWidth: '36px',
    padding: spacing.md
  },
  backdrop: {
    backgroundColor: 'rgba(17, 24, 39, 0.56)',
    inset: 0,
    position: 'fixed',
    zIndex: 1000
  },
  viewport: {
    alignItems: 'center',
    display: 'flex',
    inset: 0,
    justifyContent: 'center',
    overflowY: 'auto',
    padding: spacing.xl,
    position: 'fixed',
    zIndex: 1001
  },
  dialogPopup: {
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.borderMuted,
    borderRadius: radii.md,
    borderStyle: 'solid',
    borderWidth: '1px',
    boxShadow: '0 24px 64px rgba(17, 24, 39, 0.24)',
    boxSizing: 'border-box',
    color: colors.text,
    display: 'grid',
    fontFamily: fontFamilies.sans,
    gap: spacing.lg,
    maxWidth: '480px',
    outline: 'none',
    padding: spacing.xl,
    width: '100%'
  },
  title: {
    color: colors.text,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.lg,
    fontWeight: fontWeights.semibold,
    lineHeight: lineHeights.lg,
    margin: 0
  },
  description: {
    color: colors.textMuted,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.sm,
    lineHeight: lineHeights.sm,
    margin: 0
  },
  actions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: 'flex-end'
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: { default: colors.surfaceElevated, ':hover': colors.surfaceSubtle },
    borderColor: colors.borderMuted,
    borderRadius: radii.sm,
    borderStyle: 'solid',
    borderWidth: '1px',
    color: colors.text,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semibold,
    justifyContent: 'center',
    lineHeight: lineHeights.sm,
    paddingBlock: spacing.md,
    paddingInline: spacing.lg
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: { default: colors.primary, ':hover': colors.primaryHover },
    borderColor: 'transparent',
    borderRadius: radii.sm,
    borderStyle: 'solid',
    borderWidth: '1px',
    color: colors.onEmphasis,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semibold,
    justifyContent: 'center',
    lineHeight: lineHeights.sm,
    paddingBlock: spacing.md,
    paddingInline: spacing.lg
  },
  dangerButton: {
    alignItems: 'center',
    backgroundColor: { default: colors.danger, ':hover': '#b91c1c' },
    borderColor: 'transparent',
    borderRadius: radii.sm,
    borderStyle: 'solid',
    borderWidth: '1px',
    color: colors.onEmphasis,
    cursor: 'pointer',
    display: 'inline-flex',
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.semibold,
    justifyContent: 'center',
    lineHeight: lineHeights.sm,
    paddingBlock: spacing.md,
    paddingInline: spacing.lg
  },
  positioner: { zIndex: 1100 },
  popoverPopup: {
    backgroundColor: colors.surfaceElevated,
    borderColor: colors.borderMuted,
    borderRadius: radii.md,
    borderStyle: 'solid',
    borderWidth: '1px',
    boxShadow: '0 12px 36px rgba(17, 24, 39, 0.2)',
    boxSizing: 'border-box',
    color: colors.text,
    display: 'grid',
    fontFamily: fontFamilies.sans,
    gap: spacing.md,
    maxWidth: '320px',
    outline: 'none',
    padding: spacing.lg
  },
  tooltipPopup: {
    backgroundColor: colors.text,
    borderRadius: radii.sm,
    color: colors.surface,
    fontFamily: fontFamilies.sans,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.semibold,
    lineHeight: lineHeights.sm,
    maxWidth: '240px',
    paddingBlock: spacing.sm,
    paddingInline: spacing.md
  },
  popoverArrow: { color: colors.surfaceElevated, display: 'flex' },
  tooltipArrow: { color: colors.text, display: 'flex' },
  arrowSvg: { display: 'block' }
});
